- name: Setup CLI tools and config
  hosts: localhost
  become: no
  vars:
    the_user: "{{ ansible_user_id }}"
    asdf_version: "0.18.0"
    nodejs_version: "20.12.2"
    golang_version: "1.22.2"
    python_version: "3.12.5"
    hugo_version: "0.111.3"
  pre_tasks:
    - name: Update apt cache for Debian
      become: true
      ansible.builtin.apt:
        update_cache: true
      tags:
        - always
      when: ansible_os_family == "Debian"
    - name: Update pacman cache for Archlinux
      become: true
      community.general.pacman:
        update_cache: true
      tags:
        - always
      when: ansible_os_family == "Archlinux"
    - name: Load Vault
      ansible.builtin.include_vars:
        file: infra/vault.yml
        name: vault
      tags:
        - dotfiles
      when: dotfiles_mode == 'private'
  tasks:
    - ansible.builtin.import_tasks: tasks/core.yml
    - ansible.builtin.import_tasks: tasks/zsh.yml
    # dotfiles needs to be after zsh to not have oh-my-zsh replace zshrc file
    # and to be ready for tmux
    - ansible.builtin.import_tasks: tasks/github-cli.yml
    - ansible.builtin.import_tasks: tasks/dotfiles.yml
    - ansible.builtin.import_tasks: tasks/tmux.yml
    - ansible.builtin.import_tasks: tasks/neovim.yml
    - ansible.builtin.import_tasks: tasks/productivity-tools.yml
    - ansible.builtin.import_tasks: tasks/programming-languages.yml
