- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
  tasks:
    - ansible.builtin.import_tasks: tasks/zsh.yml
    # needs to be after zsh to not have oh-my-zsh replace zshrc file
    # and to be ready for tmux
    - ansible.builtin.import_tasks: tasks/dotfiles.yml
    - ansible.builtin.import_tasks: tasks/tmux.yml
    - ansible.builtin.import_tasks: tasks/neovim.yml
    - ansible.builtin.import_tasks: tasks/productivity-tools.yml
    - ansible.builtin.import_tasks: tasks/asdf.yml
