- hosts: localhost
  become: no
  vars:
    the_user: "{{ ansible_user_id }}"
    ubuntu_version: "{{ ansible_lsb.release }}"
  pre_tasks:
    - name: Update cache
      become: true
      ansible.builtin.apt:
        update_cache: true
    - name: Load Vault
      ansible.builtin.include_vars:
        file: infra/vault.yml
        name: secrets
      tags:
        - install
        - dotfiles
  tasks:
    - ansible.builtin.import_tasks: tasks/core.yml
    - ansible.builtin.import_tasks: tasks/zsh.yml
    # dotfiles needs to be after zsh to not have oh-my-zsh replace zshrc file
    # and to be ready for tmux
    - ansible.builtin.import_tasks: tasks/github-cli.yml
    - ansible.builtin.import_tasks: tasks/dotfiles.yml
    - ansible.builtin.import_tasks: tasks/tmux.yml
    - ansible.builtin.import_tasks: tasks/neovim.yml
    - ansible.builtin.import_tasks: tasks/productivity-tools.yml
    - ansible.builtin.import_tasks: tasks/languages.yml
    - ansible.builtin.import_tasks: tasks/apps.yml
    - ansible.builtin.import_tasks: tasks/gnome.yml
