- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
  tasks:
    - ansible.builtin.include_tasks: tasks/zsh.yml
    - ansible.builtin.include_tasks: tasks/tmux.yml
    - ansible.builtin.include_tasks: tasks/neovim.yml
    - ansible.builtin.include_tasks: tasks/dotfiles.yml
