- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
  tasks:
    - name: Install zsh
      ansible.builtin.apt:
        name: zsh
    - name: Change shell
      ansible.builtin.shell: chsh -s `which sh`
    - name: Install oh-my-zsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - name: Install tmux
      ansible.builtin.apt:
        name: tmux
    - name: Install Neovim
      ansible.builtin.apt:
        name: neovim
