- name: Add Guake repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:linuxuprising/guake
    state: present
  tags:
    - install
    - apps
    - ubuntu

- name: Update repositories cache and install Guake
  become: true
  ansible.builtin.apt:
    name: guake
    update_cache: yes
  tags:
    - install
    - apps
    - ubuntu

- name: Restore guake prefs
  ansible.builtin.shell: guake --restore-preferences $HOME/.config/guake/prefs.guake
  tags:
    - install
    - apps
    - ubuntu

# https://albertlauncher.github.io/installation/
# Ubuntu 22.04
- name: Install Albert launcher
  become: true
  ansible.builtin.apt:
    deb: https://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/amd64/albert_0.26.4-0+649.1_amd64.deb 
  tags:
    - install
    - apps
    - ubuntu
    - albert

- name: Install Google Chrome
  become: true
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  tags:
    - install
    - apps
    - ubuntu
    - chrome
