- name: Clone asdf
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    update: yes
  tags:
    - asdf

- name: Install node.js
  ansible.builtin.shell: asdf plugin add nodejs && asdf install nodejs latest:20 && asdf global nodejs $(asdf list nodejs | tail -n 1 | tr -d "*")
  tags:
    - asdf

- name: Install go
  ansible.builtin.shell: asdf plugin add golang && asdf install golang latest && asdf global golang $(asdf list golang | tail -n 1 | tr -d "*")
  tags:
    - asdf
