- name: Install System Packages (build-essential, cmake, gettext, etc.)
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - "{{ 'build-essential' if ansible_os_family == 'Debian' else 'base-devel' }}"
    - cmake
    - gettext
    - "{{ 'ninja-build' if ansible_os_family == 'Debian' else 'ninja' }}"
    - "{{ 'dconf-cli' if ansible_os_family == 'Debian' else 'dconf' }}"
  tags:
    - install
    - core
    - python
    - neovim
    - always

- name: Install tools (htop, etc.)
  become: true
  package:
    name: ["htop", "unzip", "busybox"]
  tags:
    - install
    - core
    - always
