- name: Install System Packages (build-essential, cmake, gettext, etc.)
  become: true
  apt:
    name: ["build-essential", "cmake", "gettext", "ninja-build"]
  tags:
    - install
    - neovim
    - core

- name: Install tools (htop, etc.)
  become: true
  apt:
    name: ["htop"]
  tags:
    - install
    - core

- name: Install necessary core packages for python
  become: true
  apt:
    name: ["zlib1g-dev", "libffi-dev", "libssl-dev", "libbz2-dev", "libreadline-dev", "libsqlite3-dev", "liblzma-dev"]
  tags:
    - install
    - core
    - python

