- name: Install System Packages (build-essential, cmake, gettext, etc.)
  become: true
  apt:
    name: ["build-essential", "cmake", "gettext", "ninja-build"]
  tags:
    - install
    - neovim
    - core

- name: Install tools (htop, etc.)
  become: true
  apt:
    name: ["htop", "unzip", "busybox"]
  tags:
    - install
    - core
