- name: Install Stow
  become: true
  ansible.builtin.apt:
    name: stow
  tags:
    - install
    - dotfiles

- name: Debug Dotfiles key
  debug:
    msg: "Git token starts with {{ vault.DOTFILES_PRIVATE_PAT[:10] }}..."
  tags:
    - install
    - dotfiles

- name: Clone dotfiles
  ansible.builtin.git:
    repo: "https://{{ vault.DOTFILES_PRIVATE_PAT }}@github.com/andrenbrandao/dotfiles-private.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles-private"
    recursive: yes
    update: yes
  tags:
    - install
    - dotfiles

- name: Check that the .zshrc exists
  ansible.builtin.stat:
    path: $HOME/.zshrc
  register: zshrc_stats
  tags:
    - install
    - dotfiles

- name: Remove .zshrc
  ansible.builtin.shell: rm $HOME/.zshrc
  when: zshrc_stats.stat.exists == True
  tags:
    - install
    - dotfiles

# This is needed to that the dotfiles don't end up creating this
# directory first and end up symlinking everything later added to
# it to the dotfiles repo.
- name: Create $HOME/.local/bin/ directory if it does not exist
  ansible.builtin.file:
    path: $HOME/.local/bin
    state: directory
    mode: "0775"
  tags:
    - install
    - dotfiles

# This is needed to that the dotfiles don't end up creating this
# directory first and end up symlinking everything later added to
# it to the dotfiles repo.
- name: Create $HOME/.config/systemd/ directory if it does not exist
  ansible.builtin.file:
    path: $HOME/.config/systemd/user/default.target.wants
    state: directory
    mode: "0775"
  tags:
    - install
    - dotfiles
    - systemd

- name: Stow dotfiles
  ansible.builtin.shell: cd $HOME/dotfiles-private && ./stow
  tags:
    - install
    - dotfiles
