- name: Manage Dotfiles
  tags:
    - install
    - dotfiles
  block:
    - name: Install Stow
      become: true
      ansible.builtin.package:
        name: stow

    - name: Clone dotfiles
      become: false
      ansible.builtin.git:
        repo: "https://{{ vault.DOTFILES_PRIVATE_PAT }}@github.com/andrenbrandao/dotfiles-private.git"
        dest: "{{ lookup('env', 'HOME') }}/dotfiles-private"
        recursive: yes
        update: yes
      no_log: true

    - name: Remove .zshrc if it exists
      become: false
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
        state: absent

    # This is needed to that the dotfiles don't end up creating this
    # directory first and end up symlinking everything later added to
    # it to the dotfiles repo.
    - name: Create $HOME/.local/bin/ directory if it does not exist
      become: false
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.local/bin"
        state: directory
        mode: "0775"

    # This is needed to that the dotfiles don't end up creating this
    # directory first and end up symlinking everything later added to
    # it to the dotfiles repo.
    - name: Create $HOME/.config/systemd/ directory if it does not exist
      become: false
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.config/systemd/user/default.target.wants"
        state: directory
        mode: "0775"

    - name: Stow dotfiles
      become: false
      ansible.builtin.shell: "cd {{ lookup('env', 'HOME') }}/dotfiles-private && ./stow"
