- name: Clone asdf
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    version: v0.14.0
  tags:
    - install
    - asdf
    - languages

# only needed for bash
# zsh is handled by the plugin in oh-my-zsh
- name: Configure asdf in .bashrc
  ansible.builtin.blockinfile:
    path: $HOME/.bashrc
    block: |
      . "$HOME/.asdf/asdf.sh"
      . "$HOME/.asdf/completions/asdf.bash"
  tags:
    - install
    - asdf
    - languages

- name: asdf plugin-add nodejs
  ansible.builtin.command: "asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.asdf/bin"
  tags:
    - install
    - asdf
    - languages

- name: asdf plugin-add golang
  ansible.builtin.command: "asdf plugin add golang https://github.com/asdf-community/asdf-golang.git"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.asdf/bin"
  tags:
    - install
    - asdf
    - languages

- name: asdf install nodejs
  ansible.builtin.command: "asdf install nodejs 20.12.2"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.asdf/bin"
  tags:
    - install
    - asdf
    - languages

- name: asdf install golang
  ansible.builtin.command: "asdf install golang 1.22.2"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.asdf/bin"
  tags:
    - install
    - asdf
    - languages

- name: asdf global nodejs 20.12.2
  ansible.builtin.command: "asdf global nodejs 20.12.2"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.asdf/bin"
  tags:
    - install
    - asdf
    - languages

- name: asdf global golang 1.22.2
  ansible.builtin.command: "asdf global golang 1.22.2"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.asdf/bin"
  tags:
    - install
    - asdf
    - languages

- name: Download Rust and Cargo Installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - install
    - languages

- name: Install Rust and Cargo
  ansible.builtin.shell: /tmp/sh.rustup.rs -y
  tags:
    - install
    - languages
