- name: Clone Neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "/tmp/neovim"
    version: v0.10.0
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd /tmp/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  shell: "cd /tmp/neovim && make install"
  tags:
    - install
    - neovim
