- name: Build and Install Neovim from source
  tags:
    - install
    - neovim
  when: ansible_os_family == "Debian"
  block:
    - name: Clone Neovim
      ansible.builtin.git:
        repo: "https://github.com/neovim/neovim.git"
        dest: "/tmp/neovim"
        version: v0.10.2

    - name: Build neovim
      ansible.builtin.shell: "cd /tmp/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"

    - name: Install neovim
      become: true
      ansible.builtin.shell: "cd /tmp/neovim && make install"

- name: Build and Install Neovim in Arch
  tags:
    - install
    - neovim
  when: ansible_os_family == "Archlinux"
  block:
    - name: Install neovim
      become: true
      ansible.builtin.package:
        name: neovim
