- name: Install productivity packages
  become: true
  ansible.builtin.apt:
    name: ["vim", "xclip", "tldr", "ripgrep", "fasd"]
  tags:
    - install
    - productivity

- name: Clone Fzf
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ lookup('env', 'HOME') }}/.fzf"
    update: yes
    depth: 1
  tags:
    - install
    - productivity

- name: Install fzf
  ansible.builtin.shell: $HOME/.fzf/install
  tags:
    - install
    - productivity

- name: Install Hack Nerd font
  ansible.builtin.shell: mkdir -p ~/.local/share/fonts && cd ~/.local/share/fonts && curl -fLO https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/Hack/Regular/HackNerdFont-Regular.ttf
  tags:
    - install
    - productivity
