- name: Install Productivity Tools
  tags:
    - install
    - productivity
  block:
    - name: Install productivity packages
      become: true
      ansible.builtin.package:
        name: ["vim", "tldr", "ripgrep", "fasd"]

    - name: Install Fzf
      become: false
      block:
        - name: Clone Fzf
          ansible.builtin.git:
            repo: "https://github.com/junegunn/fzf.git"
            dest: "{{ lookup('env', 'HOME') }}/.fzf"
            update: yes
            depth: 1

        - name: Install fzf
          ansible.builtin.shell: "{{ lookup('env', 'HOME') }}/.fzf/install"
