- name: Install and Configure tmux
  tags:
    - install
    - tmux
  block:
    - name: Install tmux
      become: true
      ansible.builtin.apt:
        name: tmux

    - name: Clone tpm
      become: false
      ansible.builtin.git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
        recursive: yes
        update: yes

    - name: Run tpm install scripts
      become: false
      ansible.builtin.shell: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm/scripts/install_plugins.sh"
