# GitHub Action Workflow to Verify the Ansible Playbook
# This workflow simulates setting up a new machine by running the Ansible
# playbook on a clean, headless Ubuntu runner. It's designed to catch
# issues with dependencies, commands, or repository access.

name: Verify Ansible Playbook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Runs every Monday at 08:00 UTC
    - cron: "0 8 * * 1"

  # Allows this workflow to be run manually from the Actions tab.
  workflow_dispatch:

jobs:
  verify-ubuntu:
    name: Test Ubuntu Playbook
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          # Important for PAT to be used in ansible's git clone for dotfiles-private.
          # See https://github.com/orgs/community/discussions/25240#discussioncomment-3247038.
          persist-credentials: false

      - name: Install Ansible and Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl git software-properties-common ansible

      - name: Run Ansible Playbook
        env:
          VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo "Executing the Ubuntu playbook..."

          echo "$VAULT_PASSWORD" > vault_pass.txt
          ansible-playbook ubuntu.yml --vault-password-file vault_pass.txt
          shred -u vault_pass.txt

          echo "Playbook execution finished."
